services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --upgrade -r requirements.txt
      # Create all necessary directories
      mkdir -p models templates static
      # Run direct model creation first to ensure a model exists
      echo "Creating model files with direct approach..."
      python direct_model_loader.py
      # Also run regular model creation scripts
      echo "Running standard model creation scripts..."
      python create_model_file.py
      python train_model.py
      # List current files and directories
      echo "Current directory contents:"
      ls -la
      
      # Create and verify templates directory
      mkdir -p /opt/render/project/src/templates
      mkdir -p templates
      echo "Creating template directories..."
      chmod -R 755 /opt/render/project/src/templates
      chmod -R 755 templates
      
      # Create and verify static directory
      mkdir -p /opt/render/project/src/static
      mkdir -p static
      echo "Creating static directories..."
      chmod -R 755 /opt/render/project/src/static
      chmod -R 755 static
      
      # List the directories to verify creation
      ls -la /opt/render/project/src/
      ls -la /opt/render/project/src/templates/ || echo "Templates directory is empty"
      ls -la /opt/render/project/src/static/ || echo "Static directory is empty"
      
      # Create template files in multiple locations for redundancy
      echo "Creating template files..."
      
      # Create the template file in the source directory
      cat > templates/index.html << 'EOL'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fake News Detector</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }
        .container {
            max-width: 800px;
            margin: 2rem auto;
            padding: 2rem;
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }
        .result-card {
            display: none;
            margin-top: 2rem;
            padding: 1.5rem;
            border-radius: 8px;
            background-color: #f8f9fa;
        }
        .progress {
            height: 25px;
            margin: 1rem 0;
        }
        .certainty-badge {
            font-size: 1.1rem;
            padding: 0.5rem 1rem;
            border-radius: 20px;
        }
        .loading {
            display: none;
            text-align: center;
            margin: 2rem 0;
        }
        .spinner-border {
            width: 3rem;
            height: 3rem;
        }
        .error-message {
            display: none;
            color: #dc3545;
            margin-top: 1rem;
            padding: 1rem;
            border-radius: 4px;
            background-color: #f8d7da;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-center mb-4">Fake News Detector</h1>
        <p class="text-center text-muted mb-4">Paste your news article below to analyze if it's real or fake</p>
        
        <div class="form-group">
            <textarea id="newsText" class="form-control" rows="6" placeholder="Paste your news article here..."></textarea>
        </div>
        
        <div class="text-center mt-3">
            <button id="analyzeBtn" class="btn btn-primary btn-lg">Analyze</button>
        </div>
        
        <div class="error-message" id="errorMessage"></div>
        
        <div class="loading">
            <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <p class="mt-2">Analyzing your article...</p>
        </div>
        
        <div class="result-card">
            <h3 class="text-center mb-3">Analysis Result</h3>
            <div class="text-center">
                <h4 id="prediction" class="mb-3"></h4>
                <div class="progress">
                    <div id="confidenceBar" class="progress-bar" role="progressbar" style="width: 0%"></div>
                </div>
                <p class="mt-2">Confidence: <span id="confidenceValue">0%</span></p>
                <span id="certainty" class="badge certainty-badge"></span>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('analyzeBtn').addEventListener('click', async () => {
            const text = document.getElementById('newsText').value.trim();
            if (!text) {
                showError('Please enter some text to analyze');
                return;
            }

            // Reset UI
            document.querySelector('.error-message').style.display = 'none';
            document.querySelector('.loading').style.display = 'block';
            document.querySelector('.result-card').style.display = 'none';

            try {
                const response = await fetch('/predict', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ text }),
                });

                const data = await response.json();

                if (data.status === 'error') {
                    throw new Error(data.error);
                }

                // Update UI with results
                document.getElementById('prediction').textContent = data.prediction;
                document.getElementById('prediction').className = `text-${data.prediction === 'Real News' ? 'success' : 'danger'}`;
                
                const confidence = Math.round(data.confidence * 100);
                document.getElementById('confidenceValue').textContent = `${confidence}%`;
                document.getElementById('confidenceBar').style.width = `${confidence}%`;
                document.getElementById('confidenceBar').className = `progress-bar bg-${data.prediction === 'Real News' ? 'success' : 'danger'}`;
                
                document.getElementById('certainty').textContent = data.certainty;
                document.getElementById('certainty').className = `badge certainty-badge bg-${data.certainty === 'High' ? 'success' : data.certainty === 'Moderate' ? 'warning' : 'danger'}`;
                
                document.querySelector('.result-card').style.display = 'block';
            } catch (error) {
                showError(error.message);
            } finally {
                document.querySelector('.loading').style.display = 'none';
            }
        });

        function showError(message) {
            const errorElement = document.getElementById('errorMessage');
            errorElement.textContent = message;
            errorElement.style.display = 'block';
        }
    </script>
</body>
</html>
EOL
      
      # Also create a copy in the static directory
      cp templates/index.html static/index.html
      
      # Create template files in the absolute paths
      cp templates/index.html /opt/render/project/src/templates/index.html
      cp static/index.html /opt/render/project/src/static/index.html
      
      # Set permissions
      chmod 644 templates/index.html
      chmod 644 static/index.html
      chmod 644 /opt/render/project/src/templates/index.html
      chmod 644 /opt/render/project/src/static/index.html
      
      # Verify files exist
      echo "Verifying template files:"
      ls -la templates/
      ls -la static/
      ls -la /opt/render/project/src/templates/
      ls -la /opt/render/project/src/static/
      
      # Verify model files
      echo "Verifying model files:"
      ls -la models/
      ls -la /opt/render/project/src/models/
      
      # Create a check file to verify the build process
      echo "Build completed successfully at $(date)" > build_successful.txt
      
      # Copy models to absolute path to ensure they're found
      mkdir -p /opt/render/project/src/models
      cp -f models/* /opt/render/project/src/models/
      chmod -R 755 /opt/render/project/src/models
      
      # Run the create_template.py script
      python create_template.py
    startCommand: |
      # Run the template creation script before starting the server
      python create_template.py
      # Run the direct model creation script to ensure we have model files
      python direct_model_loader.py
      # Start the server
      gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: true
      - key: FLASK_ENV
        value: production
      - key: DEBUG_TEMPLATES
        value: true
      - key: DEBUG_MODEL
        value: true
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - Procfile
        - models/**/*
        - templates/**/*
        - static/**/*
        - .gitignore
        - render.yaml
        - train_model.py
        - create_model_file.py
        - direct_model_loader.py
        - create_template.py
        - train.log
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 